### PR TITLE
Fix SubmissionManagerSpec

### LINKED ISSUE #810: Fix SubmissionManagerSpec
As a result of [this PR](https://github.com/cfpb/hmda-platform/pull/752), the test no longer works.

### PR DESCRIPTION
**Pull request by schbetsy**
Closes #810

### CODE REVIEW

**Comment by jmarin** [comment]
The problem that I see is that while this fixes the test, this change renders the `Failed` state useless, we will never reach that unless I am missing something. While we are thinking about [changing](https://github.com/cfpb/hmda-platform/issues/849) the states we need to keep a `Failed` state in the application

**Comment by schbetsy** [comment]
Yeah, that's kind of what I was trying to get at with questions 1 and 2 in my original comment. 

Under what circumstances _should_ the FSM receive `None`?

**Comment by schbetsy** [comment]
Marking as WIP so I can investigate more thoroughly.

**Comment by nickgrippin** [comment]
LGTM!

**Pull request merged**
