### PR TITLE
call DSL containedIn without wrapping domain values in a List

### PR DESCRIPTION
**Pull request by lgdean**
Basically, I got tired of seeing `List(1, 2, 3)` everywhere; it felt like clutter.  So I added this to the DSL.

Overall I think it's a good idea, but I'm open to discussion of whether it's always good to use.  In particular, please give `V347` a look and decide what you think.  Hard to judge one's own code sometimes!

### CODE REVIEW

**Comment by nickgrippin** [comment]
I can definitely see how `V347` could be confusing.  Defining the `List` there makes it clear that we're only looking for 1 or 6, but if a user sees `containedIn`, they might wonder if we were looking for any values 1 through 6.

This might be a weird naming suggestion, but maybe `oneOf`?  It reads fairly well, and might be a bit clearer to the user.  I'm open to other suggestions though, or just keeping it as is.

**Comment by kgudel** [comment]
I feel like its a nice way to clean things up a bit but I am all aboard with Nick. I also like `oneOf`.

**Comment by lgdean** [comment]
I also like `oneOf`, and then I don't have to do the awkward first/rest thing with the args.  I'll leave it alone for a little while to give others a chance to weigh in while I review other PRs, because we have a lot of inventory right now.  (If nobody weighs in, that's fine, and I declare `oneOf` the consensus in that case.)

**Comment by jmarin** [comment]
+0 from me. I see this as syntactic sugar, which _can_ be nice, but imho is not critical.

**Comment by lgdean** [comment]
Renamed to `oneOf`; thanks for the suggestion!

**Comment by nickgrippin** [comment]
LGTM

**Pull request merged**
