### PR TITLE
Fix V300

### LINKED ISSUE #385: V300 should not enforce tract="NA" for small county

### PR DESCRIPTION
**Pull request by kgudel**
Closes #385

### CODE REVIEW

**Comment by kgudel** [comment]
Requires #386

**Comment by nickgrippin** [comment]
Code LGTM.  @debseidner, does this fix look good to you?

**Comment by debseidner** [comment]
@nickgrippin @kgudel Have one question

I see this:
 when(tract not equalTo("NA")) {
        validFormat and
          validCensusTractCombination and
 -        tractStateCountyCombination and
 -        smallCounty

Is there a check that MSA, Census, County and State are all a valid combination if MSA does not = NA? Also, what does smallcounty mean there?

**Comment by kgudel** [comment]
1. Yes. `validCensusTractCombination` checks whether all geo fields are valid when MSA not "NA".

2. Small county is true if the county is marked as small and false if not.

**Comment by debseidner** [comment]
@kgudel Thanks for the explanations. @nickgrippin All good.now. Thanks again for checking.

**Pull request merged**
