### PR TITLE
V648

### LINKED ISSUE #1726: 2018 Edits: V648
Edit #: V648
Edit Type: Validity
Category: LAR
Data Fields: Sex of Co-Applicant or Co-Borrower; Sex of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname
Description:

_Instructional Text for Users_: An invalid Sex data field was reported. Please review the information below and update your file accordingly:

_Edit Logic:_

1) If Sex of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname equals 2, then Sex of Co-Applicant or Co-Borrower must equal 1, 2, 3 or 6. 
2) If Sex of Co-Applicant or Co-Borrower equals 6, then Sex of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname must equal 2.

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #1726

### CODE REVIEW

**Comment by jmarin** [comment]
Please fix Travis failures

**Comment by jmarin** [comment]
Please fix Travis failures

**Comment by jmarin** [comment]
Please fix Travis failures

**Comment by jmarin** [comment]
Now that we have the validation API hooked up, the edits need to be added to the corresponding validation engine

Also, I've had this failure in one of my PRs. Creating a new PR solved my problem

**Comment by nickgrippin** [comment]
Closing

**Pull request closed without merging**
