### PR TITLE
Changed macro API output 

### LINKED ISSUE #634: Change output for macro edits API
Macro edits don't have a list of `LAR` that fail the edit check (they are applied to all the file). Modify the API so that it only lists the macro edits, without an empty list of `LAR` in each reported error.
Depends on #633

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #634

### CODE REVIEW

**Comment by awolfe76** [comment]
@nickgrippin - can we update the API docs because of this PR? To add a macro response?

**Comment by nickgrippin** [comment]
@awolfe76: sure thing!

**Comment by nickgrippin** [comment]
So, this isn't going to match what the front end is currently using, because we don't have a model for justifications yet.  I'm not sure if that should belong in a separate ticket, or if the ticket should be changed to "match front-end api" as opposed to "list macro edits".

**Comment by awolfe76** [comment]
I think create a new issue to get the format right. This is a great first step. Thanks!

**Comment by nickgrippin** [comment]
Created #663

**Pull request merged**
