### PR TITLE
implement V340

### PR DESCRIPTION
**Pull request by lgdean**
#158 

I raised one question in a comment (which we may or may not address now, but if not, doing things this way may become a default).  I also wonder about conventions for naming tests, as these names may not follow any existing one.  (There's should vs must vs just-plain does, for one thing.  Do we want to standardize yet? Ever?)

### CODE REVIEW

**Comment by jmarin** [comment]
I would suggest asking that question you have in a comment as a GitHub ticket for better tracking, using the `question` label created for that purpose. The question you are asking is more generic than the changes reflected in this PR.

**Comment by jmarin** [comment]
On the test naming conventions, the discrepancies are a nature of organic growth. This doesn't bother me much, but if you want to prepare a pull request standardizing them that would be great. I would suggest using `MustMatchers` and `must` as language for them.

**Comment by lgdean** [comment]
removed the comment and put its question into #270

**Comment by schbetsy** [comment]
Since the LarValidityEngine is already merged (thanks!) I'd say add this to the engine, then LGTM.

**Comment by lgdean** [comment]
I'd like to add it to the engine in a different PR if that's cool with you (since I have some other validity check work in progress).

**Comment by schbetsy** [comment]
Sounds good. LGTM. @jmarin?

**Pull request merged**
