### PR TITLE
Update SubmissionStatusProtocol

### LINKED ISSUE #599: Update SubmissionProtocol to return SubmissionStatus code and message

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #599

### CODE REVIEW

**Comment by kgudel** [comment]
I tested this out and looks good for the most part. The only possible issue is that it returns `"submissionStatus"` instead of `"status"` as in the conversation in the issue.

@awolfe76

**Comment by kgudel** [comment]
Also, remember to update the API documentation.

**Comment by schbetsy** [comment]
I agree with @kgudel . According to the specification in the issue, the json field should be `status`, not `submissionStatus`.

**Comment by schbetsy** [comment]
Also, (this may be out of scope for the current PR, but) it's a definite red flag that you didn't have to update any specs to make this change. We should have tests that ensure that our API is returning responses in the correct format.

**Comment by awolfe76** [comment]
Looks 👍  to me.

**Comment by kgudel** [comment]
Looks good Nick!!!

**Pull request merged**
