### PR TITLE
V375 purchaser loan; V262 (tests and refactoring)

### PR DESCRIPTION
**Pull request by lgdean**
addresses #160 and #126 

with @schbetsy:
Implemented V375, which led to creating a `when` part of the DSL.  Then refactored V262 to use it, updating its tests first.

We'd take feedback on the `when` syntax (as we did try two different versions), or any other aspect.

### CODE REVIEW

**Comment by lgdean** [comment]
I made a branch with yet another option for `when` syntax.  I'm not convinced I like it better, but it didn't take long, so it seemed worth trying.  (And perhaps others do prefer it!  Opinions welcome.)

**Comment by jmarin** [comment]
Of these two options, I like the one you have here better. [Here](https://github.com/jmarin/hmda-platform/tree/V375-when-then) is another option I quickly put together, tests seem to still pass. Relevant changes in [`CommonDsl`](https://github.com/jmarin/hmda-platform/blob/V375-when-then/validation/src/main/scala/hmda/validation/dsl/CommonDsl.scala#L77) and [`Result`](https://github.com/jmarin/hmda-platform/blob/V375-when-then/validation/src/main/scala/hmda/validation/dsl/Result.scala#L18)

**Comment by lgdean** [comment]
Ooh, very interesting!  We had talked about when/then but hadn't tried it.  But yeah, once you move to having things on `Result` then adding `then` does make it flow in the more-typical English word order, and plus you can go back to having the `=>` which is a nice touch.

**Comment by lgdean** [comment]
I liked the idea of having the logic in `Result` so much that I put it there.  I almost changed that method body to match @jmarin's version, but then I noticed that the failure message in that case would just be "Success() " prepended to the existing failure message, which wouldn't actually make sense.  So I kept it as is, because it's less code.

**Comment by schbetsy** [comment]
LGTM

**Pull request merged**
