### PR TITLE
Add id to validation error

### PR DESCRIPTION
**Pull request by jmarin**
Adds id to validation error. For the HMDA domain:

* Loan id for `Loan Application Register` validation errors
* Agency code + respondent id for `Transmittal Sheet`
* Empty string for edits on groups of LARs (these might be refactored out completely, see #474)

### CODE REVIEW

**Comment by lgdean** [comment]
1. 👍 
2. I have some changes in progress that will have merge conflicts with this PR, so it'd be great if we could either merge this one (and #486) soon, so I can deal with the conflicts; or hold off on this one until my later change is merged.
(I am OK either way. The former is more work for me, but may make more sense for the team overall.)

**Comment by jmarin** [comment]
@lgdean I am ok waiting to merge your changes, and then updating this PR. I think your changes are much deeper in scope and quantity, so best to get than in first.

**Comment by schbetsy** [comment]
LGTM

**Comment by lgdean** [comment]
This one ended up getting merged first anyway. I dealt with the conflicts in mine (which are in #494), and it wasn't a big deal. Should be all set now.

**Comment by schbetsy** [comment]
Oh. I thought you meant this one should wait until #486 was merged, since you didn't mention #494 in your comment. Sorry.

**Comment by lgdean** [comment]
Yeah, it was confusing. I didn't mention #494 because I hadn't created it yet, as I was waiting on #486 (and was still finishing up the work).
And I didn't mention it here after creating it because I didn't think of it! :)

**Pull request merged**
