### PR TITLE
2022 Quarterly edit Q654

### LINKED ISSUE #4236: 2022 Edits: Update Q654
Edit #: Q654
Edit Type: Quality
Category: LAR
Data Fields: Debt-to-Income Ratio; Income; Action Taken
Description:

Instructional Text for Users: Please review the information below and update your file, if needed.

Edit Logic: Changes to edit logic to specify that the DTI value is not NA, Exempt (new changes in bold).

If Income is greater than $5,000 (reported as 5) and Action Taken equals 1, 2, or 8, **and the value for DTI is not NA or Exempt,** the DTI should generally be between 0 and 80.

### PR DESCRIPTION
**Pull request by PatrickGoRaft**
closes #4236

### CODE REVIEW

**Review by lchen-2101 — APPROVED** [review]
LGTM, general question, so when an edit gets updated in a new year, from the code perspective, it's treated as a brand new edit, right?

**Comment by lchen-2101** [comment]
oop, needs conflict resolution

**Review by kgudel — CHANGES_REQUESTED** [review]
Small update, but for consistency let's keep the ordering of edits in the LAR engine constant.

**Comment by PatrickGoRaft** [comment]
> LGTM, general question, so when an edit gets updated in a new year, from the code perspective, it's treated as a brand new edit, right?

thats correct @lchen-2101 , also conflict. resolved.

@kgudel  ordering corrected

**Review by kgudel — APPROVED** [review]

**Pull request merged**
