### PR TITLE
Remove JavaMail dependency and email methods

### LINKED ISSUE #1160: Remove JavaMail dependency

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #1160

### CODE REVIEW

**Comment by schbetsy** [comment]
Do we need to remove it from `project/Dependencies.scala` too?

**Comment by nickgrippin** [comment]
@schbetsy: No, those just define the Module IDs to pull in `build.sbt`.

**Comment by schbetsy** [comment]
Okay, sounds good. 

So the plan will be to just un-comment the code when the Change Request is approved?

**Comment by nickgrippin** [comment]
Yeah, that's the current plan 👍

**Pull request merged**
