### PR TITLE
Update docker-compose to use auth

### PR DESCRIPTION
**Pull request by wpears**
Includes keycloak and auth-proxy from the hmda-platform-auth repo and
maildev to allow verifying of account signups

Depends on https://github.com/cfpb/hmda-platform-ui/pull/264 and https://github.com/cfpb/hmda-platform-ui/pull/265

Setup steps:

1. Clone the `hmda-platform-ui` and `hmda-platform-auth` repos as siblings of `hmda-platform`. Make sure you have the latest.
```
my-hmda-projects/
  hmda-platform
  hmda-platform-ui
  hmda-platform-auth
```
2. `sbt clean assembly`
3. `docker-compose up`
Bonus steps, required due to hmda-platform-ui's mounted volume:
a. Go to the hmda-platform-ui directory and `npm install`
b. In the same directory, `npm run build`
4. Visit the following URLS and click advanced -> proceed (to overcome self-signed cert errors)
 - https://192.168.99.100:8443/
 - https://192.168.99.100:4443/
5. Visit http://192.168.99.100 and click "Register" when redirected to keycloak
6. Visit http://192.168.99.100:1080, open the email, and click the verifying link
7. Happiness

Note: The api is exposed at http://192.168.99.100:9090 for direct interaction/local testing but the front-end will always access it through auth-proxy.

### CODE REVIEW

**Comment by awolfe76** [comment]
@wpears - should this update the `README` too? Build instructions and "run the entire platform"?

**Comment by kgudel** [comment]
The also LGTM!

**Comment by schbetsy** [comment]
I still can't get this working. Am I the only one?

**Comment by schbetsy** [comment]
I think the setup steps should be included in the README, so people can know how to smoke test. Other than that, LGTM.

**Pull request merged**
