### PR TITLE
Allow searching by email domain only

### LINKED ISSUE #897: Institution search returning 404
With the new data added I'm seeing a 404 returned from the institution search during the registration process.

From the [sample data file](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv) it looks like 

- [bank0.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L2)
- [bank1.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L3)
- [cnbstl.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L5)
- [consumercreditunion.com](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/main/resources/demoInstitutions.csv#L103)

should return an institution. Instead I'm seeing a 404 `{"httpStatus":404,"message":"email domain consumercreditunion.com not found","path":"/institutions"}`.

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #897

### CODE REVIEW

**Comment by nickgrippin** [comment]
Travis build is currently failing on `InstitutionSearchPathSpec`, but that same tests passes locally every time.  Trying to troubleshoot.

**Comment by schbetsy** [comment]
Has anyone run this in the docker-compose setup to see whether it fixes the issue?

**Comment by awolfe76** [comment]
@schbetsy - I have not yet, but plan to first thing in the morning. But if anyone else gets a chance to, please do.

**Comment by hkeeler** [comment]
I did set it up in compose, with both this branch and https://github.com/cfpb/hmda-platform/pull/899 merged together, and it worked fine for both `bank0.com` and `bank.com`.

**Comment by hkeeler** [comment]
Also confirmed it works in Compose for the other domains @awolfe76 originally mentioned: 
* `cnbstl.com`
* `consumercreditunion.com`.

👍

**Pull request merged**
